In [1]:
import pandas as pd, numpy as np

In [2]:
ratings = pd.read_csv("Ratings.csv")

In [3]:
ratings.shape

(7, 5)

In [4]:
ratings.head()

B1  B2  B3  B4  B5
0   1   0   4   0   3
1   2   3   4   3   2
2   3   3   2   4   2
3   4   4   3   5   4
4   5   1   4   2   2

In [5]:
ratings.describe()

B1        B2        B3        B4        B5
count  7.000000  7.000000  7.000000  7.000000  7.000000
mean   3.285714  2.285714  3.142857  3.142857  3.142857
std    1.380131  1.380131  1.214986  1.772811  1.214986
min    1.000000  0.000000  1.000000  0.000000  2.000000
25%    2.500000  1.500000  2.500000  2.500000  2.000000
50%    4.000000  3.000000  4.000000  3.000000  3.000000
75%    4.000000  3.000000  4.000000  4.500000  4.000000
max    5.000000  4.000000  4.000000  5.000000  5.000000

In [6]:
from sklearn.preprocessing import StandardScaler
scalar = StandardScaler()

In [7]:
x = scalar.fit_transform(ratings)

In [8]:
x[:5,:5]

array([[-1.78885438, -1.78885438,  0.76200076, -1.91485422, -0.12700013],
       [-1.00623059,  0.55901699,  0.76200076, -0.08703883, -1.01600102],
       [-0.2236068 ,  0.55901699, -1.01600102,  0.52223297, -1.01600102],
       [ 0.55901699,  1.34164079, -0.12700013,  1.13150476,  0.76200076],
       [ 1.34164079, -1.00623059,  0.76200076, -0.69631062, -1.01600102]])

In [9]:
from sklearn.decomposition import PCA

In [10]:
pca = PCA()

In [ ]:
pca = PCA(random_state=42)

In [11]:
pca.fit(x)

PCA()

In [12]:
pca.components_

array([[-0.3274596 , -0.48982545,  0.45663627, -0.56625117, -0.3516876 ],
       [ 0.76434418,  0.09246185,  0.41249826,  0.10582543, -0.47526303],
       [-0.47957573,  0.50848413, -0.06353977,  0.2091544 , -0.68093182],
       [ 0.21245628, -0.42239215, -0.76324465, -0.1078077 , -0.42694532],
       [-0.18280492, -0.5608481 ,  0.18641032,  0.78281066, -0.06701072]])

In [13]:
pca.explained_variance_ratio_

array([5.92796465e-01, 1.63738263e-01, 1.61138433e-01, 8.21840061e-02,
       1.42831615e-04])

In [14]:
pc2 = PCA(n_components=3, random_state=42)

In [15]:
newdata = pc2.fit_transform(x)