<h2 style = "color : Brown"> Creating NumPy Arrays </h2 >



 The following ways are commonly used when you know the size of the array beforehand:
* ```np.ones()```: Create array of 1s
* ```np.zeros()```: Create array of 0s
* ```np.random.random()```: Create array of random numbers
* ```np.arange()```: Create array with increments of a fixed step size
* ```np.linspace()```: Create array of fixed length

In [1]:
import numpy as np

##### Tip: Use help to see the syntax when required

In [2]:
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C')
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of ones with the given shape, dtype, and order.
    
    See Also
    --------
    ones_like : Return an array of ones with shape and type of input.
    empty : Return a new uninitialized array.
    zeros : Return a new array setting values to zero.
    full : Return a new array of given shape filled with value.
    
    
    Examples
    --------
   

##### Creating a 1 D array of ones

In [3]:
arr = np.ones(5)
arr

array([1., 1., 1., 1., 1.])

##### Notice that, by default, numpy creates data type = float64



In [4]:
arr.dtype

dtype('float64')

##### Can provide dtype explicitly using dtype


In [5]:
arr = np.ones(5, dtype=int)
arr

array([1, 1, 1, 1, 1])

In [6]:
arr.dtype

dtype('int64')

##### Creating a 5  x 3 array of ones


In [7]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

##### Creating array of zeros

In [8]:
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [9]:
# convert the type into integer.
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [12]:
# Create a list of integers range between 1 to 5.
list(range(1,5))

[1, 2, 3, 4]

In [13]:
np.arange(3)

array([0, 1, 2])

In [14]:
np.arange(3.0)

array([0., 1., 2.])

##### Notice that 3 is included, 35 is not, as in standard python lists

From 3 to 35 with a step of 2

In [20]:
np.arange(3,35,2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33])

##### Array of random numbers 


In [21]:
np.random.randint(2, size=10)

array([0, 1, 0, 1, 1, 1, 0, 0, 0, 0])

In [24]:
np.random.randint(3,5, size=10)

array([3, 3, 3, 3, 4, 3, 3, 3, 3, 4])

##### 2D Array of random numbers 


In [2]:
x = np.random.random([5,50])
x

array([[0.26912392, 0.31045734, 0.68596508, 0.8371639 , 0.58751429,
        0.74033206, 0.71869575, 0.0736842 , 0.93972133, 0.63653537,
        0.41612793, 0.40765678, 0.82517105, 0.01680294, 0.16398241,
        0.3182415 , 0.46048062, 0.89079668, 0.82779185, 0.87315543,
        0.37963134, 0.17790105, 0.98347108, 0.25518432, 0.73905684,
        0.72976877, 0.95718799, 0.77604582, 0.67313418, 0.12328936,
        0.7110664 , 0.03251849, 0.96339929, 0.05250636, 0.31370491,
        0.83353998, 0.9026315 , 0.69561692, 0.7490543 , 0.17665497,
        0.10555733, 0.30369621, 0.42881754, 0.55634972, 0.74798597,
        0.62811834, 0.39511031, 0.60526745, 0.8233965 , 0.22993756],
       [0.05652004, 0.32242884, 0.81808261, 0.86858393, 0.55316642,
        0.03155641, 0.63747029, 0.39085309, 0.95388661, 0.03810759,
        0.37795796, 0.48756444, 0.27588836, 0.05697329, 0.54367934,
        0.241165  , 0.99473788, 0.55170259, 0.51348359, 0.75712606,
        0.60778769, 0.52328125, 0.14256568, 0.3

In [8]:
x.shape

(1, 50)

###### Sometimes, you know the length of the array, not the step size

Array of length 20 between 1 and 10

In [27]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

<h2 style = "color : Sky blue"> Exercises </h2>



Apart from the methods mentioned above, there are a few more NumPy functions that you can use to create special NumPy arrays:

-  `np.full()`: Create a constant array of any number ‘n’
-  `np.tile()`: Create a new array by repeating an existing array for a particular number of times
-  `np.eye()`: Create an identity matrix of any dimension
-  `np.random.randint()`: Create a random array of integers within a particular range