In [34]:
import numpy as np
import pandas as pd

In [5]:
np.ones((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
np.arange(1, 10, 3)

array([1, 4, 7])

In [11]:
np.random.randint(3, size = 10)

array([0, 2, 1, 1, 1, 1, 0, 0, 2, 1])

In [18]:
np.full?

In [19]:
np.full((3,3), 10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [20]:
np.tile?

In [21]:
np.eye?

In [25]:
a1 = np.array([10,20,30,40,50])
a2 = np.arange(5)

In [23]:
print (array1.shape)

(5,)


In [26]:
np.hstack((a1, a2))

array([10, 20, 30, 40, 50,  0,  1,  2,  3,  4])

In [28]:
np.vstack((a1,a2))

array([[10, 20, 30, 40, 50],
       [ 0,  1,  2,  3,  4]])

## Pandas

In [29]:
cars_per_cap = [809, 731, 588, 18, 200, 70, 45]
country = ['United States', 'Australia', 'Japan', 'India', 'Russia', 'Morocco', 'Egypt']
drives_right = [True, False, False, False, True, True, True]

In [30]:
data = {"cars_per_cap": cars_per_cap, "country": country, "drives_right": drives_right}

In [31]:
data

{'cars_per_cap': [809, 731, 588, 18, 200, 70, 45],
 'country': ['United States',
  'Australia',
  'Japan',
  'India',
  'Russia',
  'Morocco',
  'Egypt'],
 'drives_right': [True, False, False, False, True, True, True]}

In [35]:
data_df = pd.DataFrame(data)

In [47]:
data_df['cars_per_cap']

0    809
1    731
2    588
3     18
4    200
5     70
6     45
Name: cars_per_cap, dtype: int64